webtalk_init -webtalk_dir /home/valois/Desktop/home/git/predefined/2Ch8Way-1.0.3/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Mar 7 16:27:26 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211168030_1777516030_210664724_025" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9e7n25i0q3bc0uq7485bi1f0v" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394.522 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1520457311000" -context "sdk\\\\bsp/1520457311000"
webtalk_add_data -client sdk -key hwid -value "1518639241000" -context "sdk\\\\bsp/1520457311000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1520457311000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1520457311000"
webtalk_add_data -client sdk -key uid -value "1520457312000" -context "sdk\\\\application/1520457312000"
webtalk_add_data -client sdk -key hwid -value "1518639241000" -context "sdk\\\\application/1520457312000"
webtalk_add_data -client sdk -key bspid -value "1520457311000" -context "sdk\\\\application/1520457312000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1520457312000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1520457312000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1520457312000"
webtalk_transmit -clientid 639581910 -regid "211168030_1777516030_210664724_025" -xml /home/valois/Desktop/home/git/predefined/2Ch8Way-1.0.3/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/valois/Desktop/home/git/predefined/2Ch8Way-1.0.3/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/valois/Desktop/home/git/predefined/2Ch8Way-1.0.3/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
